apiVersion: v1
kind: Service
metadata:
  name: {{ include "mnemoca.fullname" . }}
  labels: {{- include "mnemoca.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
  selector: {{- include "mnemoca.selectorLabels" . | nindent 4 }}
